<?php namespace App\Http\Controllers\Api;


use App\Http\Controllers\Controller;
use App\Models\Supplier;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class SupplierController extends Controller
{
    public function login (Request $request) {

        $user = Supplier::where('email',$request->email)->first();
        if ($user) {
            if (Hash::check($request->password, $user->password)) {
                $token = $user->createToken('QWery')->accessToken;
                $user->current_token = $token;
                $user->save();
                $response = ['success' => TRUE, 'user'=>$user];

                return response($response, 200);
            } else {
                $response = ['success' => FALSE,"message" => "Password mismatch"];
                return response($response, 200);
            }
        } else {
            $response = ['success' => FALSE,"message" =>'User does not exist'];
            return response($response, 200);
        }
    }


    public function reservations()
    {
        return parent::staticData(); // TODO: Change the autogenerated stub
    }

}
